//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 04:27:31 PM CET 
//


package com.mdl.parserDC;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for centerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="centerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employees" type="{http://www.hlbexpress.com/namespaces/HLB-dispatching-centers}employeesType"/>
 *         &lt;element name="trolleys" type="{http://www.hlbexpress.com/namespaces/HLB-dispatching-centers}trolleysType"/>
 *         &lt;element name="vehicles" type="{http://www.hlbexpress.com/namespaces/HLB-dispatching-centers}vehiclesType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Li�ge"/>
 *             &lt;enumeration value="Hasselt"/>
 *             &lt;enumeration value="Arlon"/>
 *             &lt;enumeration value="Namur"/>
 *             &lt;enumeration value="Mons"/>
 *             &lt;enumeration value="Wavre"/>
 *             &lt;enumeration value="Louvain"/>
 *             &lt;enumeration value="Gand"/>
 *             &lt;enumeration value="Anvers"/>
 *             &lt;enumeration value="Bruges"/>
 *             &lt;enumeration value="A�roport-Bruxelles"/>
 *             &lt;enumeration value="A�roport-Li�ge"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "centerType", propOrder = {
    "employees",
    "trolleys",
    "vehicles"
})
public class CenterType {

    @XmlElement(required = true)
    protected EmployeesType employees;
    @XmlElement(required = true)
    protected TrolleysType trolleys;
    @XmlElement(required = true)
    protected VehiclesType vehicles;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the employees property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeesType }
     *     
     */
    public EmployeesType getEmployees() {
        return employees;
    }

    /**
     * Sets the value of the employees property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeesType }
     *     
     */
    public void setEmployees(EmployeesType value) {
        this.employees = value;
    }

    /**
     * Gets the value of the trolleys property.
     * 
     * @return
     *     possible object is
     *     {@link TrolleysType }
     *     
     */
    public TrolleysType getTrolleys() {
        return trolleys;
    }

    /**
     * Sets the value of the trolleys property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrolleysType }
     *     
     */
    public void setTrolleys(TrolleysType value) {
        this.trolleys = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link VehiclesType }
     *     
     */
    public VehiclesType getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehiclesType }
     *     
     */
    public void setVehicles(VehiclesType value) {
        this.vehicles = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
