//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 04:27:31 PM CET 
//


package com.mdl.parserDC;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dimension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dimension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="volume" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="usefullength" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="usefulwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="usefulheight" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="totalheight" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimension")
public class Dimension {

    @XmlAttribute(name = "volume", required = true)
    protected float volume;
    @XmlAttribute(name = "usefullength", required = true)
    protected float usefullength;
    @XmlAttribute(name = "usefulwidth", required = true)
    protected float usefulwidth;
    @XmlAttribute(name = "usefulheight", required = true)
    protected float usefulheight;
    @XmlAttribute(name = "totalheight")
    protected Float totalheight;

    /**
     * Gets the value of the volume property.
     * 
     */
    public float getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     */
    public void setVolume(float value) {
        this.volume = value;
    }

    /**
     * Gets the value of the usefullength property.
     * 
     */
    public float getUsefullength() {
        return usefullength;
    }

    /**
     * Sets the value of the usefullength property.
     * 
     */
    public void setUsefullength(float value) {
        this.usefullength = value;
    }

    /**
     * Gets the value of the usefulwidth property.
     * 
     */
    public float getUsefulwidth() {
        return usefulwidth;
    }

    /**
     * Sets the value of the usefulwidth property.
     * 
     */
    public void setUsefulwidth(float value) {
        this.usefulwidth = value;
    }

    /**
     * Gets the value of the usefulheight property.
     * 
     */
    public float getUsefulheight() {
        return usefulheight;
    }

    /**
     * Sets the value of the usefulheight property.
     * 
     */
    public void setUsefulheight(float value) {
        this.usefulheight = value;
    }

    /**
     * Gets the value of the totalheight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTotalheight() {
        return totalheight;
    }

    /**
     * Sets the value of the totalheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTotalheight(Float value) {
        this.totalheight = value;
    }

}
