//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 04:27:31 PM CET 
//


package com.mdl.parserDC;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employeeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employeeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="homeaddress" type="{http://www.hlbexpress.com/namespaces/HLB-dispatching-centers}addressType"/>
 *         &lt;element name="role">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="pr�pos�"/>
 *               &lt;enumeration value="coursier"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unavailabilities" type="{http://www.hlbexpress.com/namespaces/HLB-dispatching-centers}unavailabilitiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idemployee" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="firstname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lastname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="birthdate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="phone" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employeeType", propOrder = {
    "homeaddress",
    "role",
    "unavailabilities"
})
public class EmployeeType {

    @XmlElement(required = true)
    protected AddressType homeaddress;
    @XmlElement(required = true)
    protected String role;
    protected UnavailabilitiesType unavailabilities;
    @XmlAttribute(name = "idemployee", required = true)
    protected String idemployee;
    @XmlAttribute(name = "firstname", required = true)
    protected String firstname;
    @XmlAttribute(name = "lastname", required = true)
    protected String lastname;
    @XmlAttribute(name = "birthdate", required = true)
    protected String birthdate;
    @XmlAttribute(name = "phone", required = true)
    protected String phone;

    /**
     * Gets the value of the homeaddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getHomeaddress() {
        return homeaddress;
    }

    /**
     * Sets the value of the homeaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setHomeaddress(AddressType value) {
        this.homeaddress = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the unavailabilities property.
     * 
     * @return
     *     possible object is
     *     {@link UnavailabilitiesType }
     *     
     */
    public UnavailabilitiesType getUnavailabilities() {
        return unavailabilities;
    }

    /**
     * Sets the value of the unavailabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnavailabilitiesType }
     *     
     */
    public void setUnavailabilities(UnavailabilitiesType value) {
        this.unavailabilities = value;
    }

    /**
     * Gets the value of the idemployee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdemployee() {
        return idemployee;
    }

    /**
     * Sets the value of the idemployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdemployee(String value) {
        this.idemployee = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthdate(String value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

}
