//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 04:27:31 PM CET 
//


package com.mdl.parserDC;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hlbexpress.DC package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Centers_QNAME = new QName("http://www.hlbexpress.com/namespaces/HLB-dispatching-centers", "centers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hlbexpress.DC
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CentersType }
     * 
     */
    public CentersType createCentersType() {
        return new CentersType();
    }

    /**
     * Create an instance of {@link TrolleysType }
     * 
     */
    public TrolleysType createTrolleysType() {
        return new TrolleysType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link VehiclesType }
     * 
     */
    public VehiclesType createVehiclesType() {
        return new VehiclesType();
    }

    /**
     * Create an instance of {@link TrolleyType }
     * 
     */
    public TrolleyType createTrolleyType() {
        return new TrolleyType();
    }

    /**
     * Create an instance of {@link UnavailabilityType }
     * 
     */
    public UnavailabilityType createUnavailabilityType() {
        return new UnavailabilityType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link UnavailabilitiesType }
     * 
     */
    public UnavailabilitiesType createUnavailabilitiesType() {
        return new UnavailabilitiesType();
    }

    /**
     * Create an instance of {@link EmployeesType }
     * 
     */
    public EmployeesType createEmployeesType() {
        return new EmployeesType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CenterType }
     * 
     */
    public CenterType createCenterType() {
        return new CenterType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CentersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hlbexpress.com/namespaces/HLB-dispatching-centers", name = "centers")
    public JAXBElement<CentersType> createCenters(CentersType value) {
        return new JAXBElement<CentersType>(_Centers_QNAME, CentersType.class, null, value);
    }

}
