//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.14 at 04:24:38 PM CET 
//

package com.mdl.parserSS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for clientType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="clientType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.hlbexpress.com/namespaces/HLB-head-office}addressType"/>
 *         &lt;element name="account" type="{http://www.hlbexpress.com/namespaces/HLB-head-office}accountType"/>
 *         &lt;element name="profile" type="{http://www.hlbexpress.com/namespaces/HLB-head-office}profileType"/>
 *         &lt;element name="pickups" type="{http://www.hlbexpress.com/namespaces/HLB-head-office}pickupsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lastname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="firstname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="birthdate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="phone" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "clientType", propOrder = {
        "address",
        "account",
        "profile",
        "pickups"
} )
public class ClientType {

    @XmlElement( required = true )
    protected AddressType          address;
    @XmlElement( required = true )
    protected AccountType          account;
    @XmlElement( required = true )
    protected ProfileType          profile;
    protected PickupsType          pickups;
    @XmlAttribute( name = "lastname", required = true )
    protected String               lastname;
    @XmlAttribute( name = "firstname", required = true )
    protected String               firstname;
    @XmlAttribute( name = "birthdate", required = true )
    @XmlSchemaType( name = "date" )
    protected XMLGregorianCalendar birthdate;
    @XmlAttribute( name = "phone", required = true )
    protected String               phone;

    /**
     * Gets the value of the address property.
     * 
     * @return possible object is {@link AddressType }
     * 
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *            allowed object is {@link AddressType }
     * 
     */
    public void setAddress( AddressType value ) {
        this.address = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return possible object is {@link AccountType }
     * 
     */
    public AccountType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *            allowed object is {@link AccountType }
     * 
     */
    public void setAccount( AccountType value ) {
        this.account = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return possible object is {@link ProfileType }
     * 
     */
    public ProfileType getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *            allowed object is {@link ProfileType }
     * 
     */
    public void setProfile( ProfileType value ) {
        this.profile = value;
    }

    /**
     * Gets the value of the pickups property.
     * 
     * @return possible object is {@link PickupsType }
     * 
     */
    public PickupsType getPickups() {
        return pickups;
    }

    /**
     * Sets the value of the pickups property.
     * 
     * @param value
     *            allowed object is {@link PickupsType }
     * 
     */
    public void setPickups( PickupsType value ) {
        this.pickups = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLastname( String value ) {
        this.lastname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFirstname( String value ) {
        this.firstname = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setBirthdate( XMLGregorianCalendar value ) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPhone( String value ) {
        this.phone = value;
    }

}
